# Generated by Django 6.0.3 on 2026-04-07 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_supervisions', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to=settings.AUTH_USER_MODEL)),
                ('workplace_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_supervisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
